[package]
name = "asset"
version = "0.1.0"
edition = "2021"

[dependencies]
meshopt = "0.1.9"
bincode = "1.3.3"
eyre = "0.6.8"
glam = { version = "0.24.2", features = ["bytemuck", "serde"] }
serde = { version = "1.0.183", features = ["derive"] }
bytemuck = "1.14.0"